version: '3.8'

services:
  backend:
    build: .
    container_name: dayflow_backend
    ports:
      - "4000:4000"
    env_file:
      - .env
    command: npm run dev:backend
    volumes:
      - ./backend/src:/app/backend/src
    networks:
      - dayflow_network
    extra_hosts:
      - "aws-0-ap-northeast-1.pooler.supabase.com:54.64.190.72"

  frontend:
    build: .
    container_name: dayflow_frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:4000/api
    command: >
      sh -c "node frontend/node_modules/prisma/build/index.js generate --schema=database/prisma/schema.prisma &&
      npm run dev:frontend"
    volumes:
      - ./frontend/src:/app/frontend/src
      - ./database/prisma:/app/database/prisma
    depends_on:
      - backend
    networks:
      - dayflow_network
    extra_hosts:
      - "aws-0-ap-northeast-1.pooler.supabase.com:54.64.190.72"

networks:
  dayflow_network:
    driver: bridge
